---
- hosts: localhost
  tasks: 
    - name: retry test
      uri:
        url: http://localhost:8000/current.json
        method: GET
        status_code: 200
        return_content: true
        body_format: json
      retries: 3
      delay: 5
      register: content
      until: content.json.state | default({}) == "Off"
      retries: 10
      delay: 5
    - debug:
        msg: "{{ content }}"



 - name: Check that the somefile.conf exists
      stat:
        path: /root/.uefi
      register: stat_result
      retries: 10
      delay: 25
      until: stat_result.stat.exists
      delegate_to: ubuntu
      become: yes
      remote_user: test
        
    - name: Wait for the reboot and reconnect 
      wait_for:
        port: 22
        host: "ubuntu"
        search_regex: OpenSSH
        delay: 10
        timeout: 60
      connection: local
