---
- hosts: localhost
  tasks: 
    - name: retry test
      uri:
        url: http://localhost:8000/current.json
        method: GET
        status_code: 200
        return_content: true
        body_format: json
      retries: 3
      delay: 5
      register: content
      until: content.json.state | default({}) == "Off"
      retries: 10
      delay: 5
    - debug:
        msg: "{{ content }}"
